const mainheading = document.getElementById("main-heading");
mainheading.textContent = 'Fruit World';
mainheading.style.color = 'orange';
const header = document.getElementById("header");
header.style.backgroundColor = 'green';
header.style.borderBottom = 'solid orange';
document.getElementById('basket-heading').style.color = 'green';
const thanks = document.getElementById('thanks');
thanks.innerHTML = '<p>Please visit us again</p>'
